# Generated by Django 5.1.3 on 2024-12-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='address',
        ),
    ]
