services:
  - type: web
    name: store
    env: python
    buildCommand: "python manage.py collectstatic && python manage.py migrate"
    startCommand: "gunicorn store.wsgi:application"
    envVars:
      - key: SECRET_KEY
        fromEnvironment: SECRET_KEY
      - key: DATABASE_URL
        fromEnvironment: DATABASE_URL
      - key: ALLOWED_HOSTS
        fromEnvironment: ALLOWED_HOSTS
    staticAssets:
      root: /staticfiles
      paths:
        - /static